### ISSUE TITLE
Settings MYSQL Config file are not optimal for i-doit

### ISSUE THREAD

**Issue by Invidia1990** [Gubaer/docker-i-doit#1]
i-doit Installation will work, but they warn about the configuration of mysql.

This points should be diffrent:

max_allowed_packet should be at least 32M (currently 16.00M)!
query_cache_limit should be at least 4M (currently 1.00M)!

**Comment by Gubaer** [comment]
I today release a new docker image for i-doit 1.8. In this image the configuration values `max_allowed`and `query_cache` are now configured.
