### ISSUE TITLE
i-doit version 1.8

### ISSUE THREAD

**Issue by BrunoBieri** [Gubaer/docker-i-doit#2]
i-doit is released in version 1.8 now. Is there a plan to update the docker image as well?
Maybe use this link (currently active 30.01.2017):
https://sourceforge.net/projects/i-doit/files/i-doit/1.8/idoit-open-1.8.zip/download

**Comment by Gubaer** [comment]
I'll see what I can do. An additional Dockerfile to build a docker image for i-doit 1.8 and corresponding docker image on docker hub could be added.

**Comment by Gubaer** [comment]
I've published a new docker image for i-doit 1.8. Refer to the README.

**Comment by BrunoBieri** [comment]
Perfect thanks a lot!
